#!/bin/sh
echo "> Installing maven"
wget apache.rediris.es/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
cd /module
tar -xzf apache-maven-3.3.3-bin.tar.gz -C /opt/sds
echo "export M2_HOME=/opt/sds/apache-maven-3.3.3" >> /home/vagrant/.bashrc
source ~/.bashrc
echo "export PATH=/opt/sds/apache-maven-3.3.3/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin" >> /home/vagrant/.bashrc

echo "> Starting MongoDB"
echo "smallfiles=true" >> /etc/mongod.conf
/sbin/service mongod start

echo "> Starting ElasticSearch"
/sbin/service elasticsearch start
echo "http.cors.enabled: true" >> /etc/sds/elasticsearch/elasticsearch.yml
/opt/sds/elasticsearch/bin/./plugin -install royrusso/elasticsearch-HQ
/opt/sds/elasticsearch/bin/./plugin -install mobz/elasticsearch-head

echo "> Installing redis-server"
/usr/bin/yum -y install redis

echo "> Installing rabbitmq-server"
/usr/bin/yum -y install rabbitmq-server
/sbin/service rabbitmq-server start

echo "> Installing kibana"
wget https://download.elastic.co/kibana/kibana/kibana-3.1.2.tar.gz
cd /module
tar -xzf kibana-3.1.2.tar.gz -C /opt/sds

echo "> Installing nginx"
/usr/bin/yum -y install nginx

cd /etc/nginx/conf.d/
sed -i "s|/usr/share/nginx/html|/opt/sds/kibana-3.1.2|g" default.conf
/sbin/service nginx start

rm -f /etc/udev/rules.d/70-persistent-net.rules
echo "> Installing Sparta"
/usr/bin/yum -y install stratio-sparta
/sbin/chkconfig --add sparta
/sbin/chkconfig  sparta on
/sbin/chkconfig  zookeeper on
/sbin/chkconfig --list
service zookeeper start
service sparta start

yum clean all
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY
