#!/bin/bash

INFO "[MARATHON-SSO] Obtaining and setting Mesos security configuration"

### Get Mesos user and pass
getPass "userland" "$SERVICE_ID_WITH_PATH" "sso"

SSO_USER=${SERVICE_ID_WITH_PATH_NORM}_SSO_USER
SSO_PASS=${SERVICE_ID_WITH_PATH_NORM}_SSO_PASS

export MARATHON_SSO_USERNAME=${!SSO_USER}
echo "export MARATHON_SSO_USERNAME=${MARATHON_SSO_USERNAME}" >> ${VARIABLES}
export MARATHON_SSO_PASSWORD=${!SSO_PASS}
echo "export MARATHON_SSO_PASSWORD=${MARATHON_SSO_PASSWORD}" >> ${VARIABLES}

