#!/bin/bash

INFO "[MESOS-SECURITY] Obtaining and setting Mesos security configuration"

### Get Mesos user and pass
getPass "userland" "$SERVICE_ID_WITH_PATH" "mesos"

MESOS_USER=${SERVICE_ID_WITH_PATH_NORM}_MESOS_USER
MESOS_PASS=${SERVICE_ID_WITH_PATH_NORM}_MESOS_PASS

export SPARK_MESOS_PRINCIPAL=${!MESOS_USER}

echo "export SPARK_SECURITY_MESOS_ENABLE=true" >> ${VARIABLES}
echo "export SPARK_SECURITY_MESOS_VAULT_PATH=\"$SPARTA_SECURITY_VAULT_PASSWORDS_PATH/$SERVICE_ID_WITH_PATH/mesos\"" >> ${VARIABLES}
echo "export SPARK_MESOS_PRINCIPAL=${SPARK_MESOS_PRINCIPAL}" >> ${VARIABLES}
export SPARK_MESOS_SECRET=${!MESOS_PASS}
echo "export SPARK_MESOS_SECRET=${SPARK_MESOS_SECRET}" >> ${VARIABLES}

if [[ ! -v SPARK_MESOS_ROLE ]]; then
   export SPARK_MESOS_ROLE=$TENANT_NAME
fi
echo "export SPARK_MESOS_ROLE=${SPARK_MESOS_ROLE}" >> ${VARIABLES}

