/*
 * © 2017 Stratio Big Data Inc., Sucursal en España. All rights reserved.
 *
 * This software – including all its source code – contains proprietary information of Stratio Big Data Inc., Sucursal en España and may not be revealed, sold, transferred, modified, distributed or otherwise made available, licensed or sublicensed to third parties; nor reverse engineered, disassembled or decompiled, without express written authorization from Stratio Big Data Inc., Sucursal en España.
 */
export const icons: any = {
    Kafka: '\uE645',
    WebSocket: '\ue078',
    Print: '\uE64A',
    FileSystem: '\uE95E',
    Jdbc: '\uE602',
    CSV: '\uE9AF',
    Csv: '\uE9AF',
    Cube: '\ue079',
    MongoDb: '\uE623',
    Parquet: '\uE649',
    Postgres: '\uE9A5',
    Redis: '\uE64B',
    Filter: '\uE616',
    Union: '\uE9B4',
    Test: '\uE062',
    Crossdata: '\ue634',
    Distinct: '\ue651',
    Casting: '\uE96C',
    Explode: '\uE9A0',
    Split: '\uE102',
    Intersection: '\uE9AE',
    Http: '\uE94C',
    OrderBy: '\uE635',
    JsonPath: '\uE9B1',
    Repartition: '\uE9AD',
    Select: '\uE9B3',
    Persist: '\uE9B2',
    Window: '\uE9B5',
    Json: '\uE96A',
    Avro: '\uE93D',
    Text: '\ue034',
    Trigger: '\uE94E',
    Checkpoint: '\ue61b',
    Datetime: '\ue64d',
    Custom: '\ue60a',
    ElasticSearch: '\ue624',
    DropColumns: '\ue123',
    DropDuplicates: '\ue908',
    AddColumns: '\ue104',
    DataProfiling: '\uE091',
    BasicDataQuality: '\uE94D',
    InitNulls: '\ue919',
    Join: '\ue98B',
    DropNulls: '\ue084',
    QueryBuilder: '\uE932',
    Xml: '\ue969',
    Rest: '\ue650',
    SFTP: '\uE97E'
};
